console.log("");
console.log("BOOLEAN() CONVERSION");
console.log("Boolean(0) =    ", Boolean(0));
console.log("Boolean(-0) =    ", Boolean(-0));
console.log("Boolean(NaN) =    ", Boolean(NaN));
console.log("Boolean('') =    ", Boolean(''));
console.log("Boolean('0') =    ", Boolean('0'));
console.log("Boolean('false') =    ", Boolean('false'));
console.log("Boolean(true) =    ", Boolean(true));
console.log("Boolean(false) =    ", Boolean(false));
console.log("Boolean('hello') =    ", Boolean('hello'));
console.log("Boolean(null) =    ", Boolean(null));
console.log("Boolean(undefined) =    ", Boolean(undefined));
console.log("Boolean([]) =    ", Boolean([]));
console.log("Boolean({}) =    ", Boolean({}));
console.log("");